add tellorrng cli support
tellor-io/telliot-feed-examples pull request #197
Opened 2022-05-12 13:32 UTC by tkernell

- adds support for reporting TellorRNG values using telliot cli
- use commands: `--rng-timestamp`, `-rngts`, or `rng_timestamp` followed by the desired timestamp argument

2022-05-16 13:35 UTC, oraclown commented on src/telliot_feed_examples/sources/blockhash_aggregator.py
> +    def setTimestamp(self, timestamp: int) -> None:
Small thing, but Python convention is snake case, so it would be `set_timestamp` instead of `setTimestamp`

2022-05-16 13:35 UTC, oraclown requested changes
Thanks for this, @tkernell !

2022-05-19 13:16 UTC, oraclown approved these changes
Nice

2022-05-19 13:16 UTC, merged

2022-05-20 14:21 UTC, tkernell commented
thanks owen